#!/usr/bin/env sh

      case "$1" in
      up)
          ${_ pamixer} -i "$2"
          ;;
      down)
          ${_ pamixer} -d "$2"
          ;;
      toggle-mute)
          ${_ pamixer} -t
          ;;
      esac

      volume="$(${_ pamixer} --get-volume)"
      isMuted="$(${_ pamixer} --get-mute)"

      if [ "$isMuted" = "true" ]; then
          ${dunst}/bin/dunstify -r 2593 \
              -u normal \
              -a "VOLUMECTL" "Muted" \
              -i audio-volume-muted-symbolic
      else
          ${dunst}/bin/dunstify -r 2593 \
              -u normal \
              -a "VOLUMECTL" "Volume: " \
              -h int:value:"$volume" \
              -i audio-volume-high-symbolic

          ${libcanberra-gtk3}/bin/canberra-gtk-play -i dialog-error -d "error"
      fi
